### ISSUE TITLE
Video cannot load in all browsers.

### ISSUE THREAD

**Issue by naevid** [juthawong/Defa-Protector-Protect-HTML5-Video-From-Download#1]
I test, Defa script in many players,  php scripts,  latest version of modern browsers, it doesn't play video.

**Comment by juthawong** [comment]
Do your server have http_response_header and get_header function without those our software cannot fetch and dump video.

Secondly try to access your defavid.php from www.example.com/defavid.php or defa.example.com/defavid that it accessible or not as well as enable.php

Hope this help man

**Comment by juthawong** [comment]
Do your server have http_response_header and get_header function without those our software cannot fetch and dump video.

Secondly try to access your defavid.php from www.example.com/defavid.php or defa.example.com/defavid that it accessible or not as well as enable.php

Hope this help man

**Comment by juthawong** [comment]
If you case is very important and want our trained technician to fix here http://www.juthawong.com/ampare-engine-service-partner-list/

or in case you want to fix by yourself.



Read our faq : http://www.juthawong.com/defa-protector-faq/

or do our first aid in case it help
A

**Comment by juthawong** [comment]
Our first aid. Pasting on mobile is very hard from my phone

1. Update Wordpress to 4.1.1
2. Try disable all the plugin except defa protector
3.Try using wordpress default theme
4.Try update Defa Protector to latest version which we do a lot of bug fixes
Defa Protector Latest version is 6.1.
You can active install on wordpress or download from sourceforge.
5. Dont use the file that you use to install on one site to another site. It might cause a problem. Please redownload and install
6.Try copy video url when activated defa protector and paste on new tab browser. If it return not found mean path is wrong. If forbidden mean .htaccess protect it from access the file. try backup .htaccess and delete .htaccess 
7.In chrome developer console(F12) Try open network tab. Search for enable.php and defavid.php if both return code 200 means everything is okay if not mean one of these are broken. You should reinstall and check for htaccess rule

Hope this help

If you case is very important and want our trained technician to fix here http://www.juthawong.com/ampare-engine-service-partner-list/

or in case you want to fix by yourself.



Read our faq : http://www.juthawong.com/defa-protector-faq/

or do our first aid in case it help

**Comment by juthawong** [comment]
Sorry I am answer from my phone. It very hard to type here
